Feature/survey
EBombo/ebombo-events pull request #348
Opened 2022-09-20 00:56 UTC by sebastianmendo1995

https://www.notion.so/ebombo/ENCUESTAS-Empezar-el-dise-o-events-6d22854e436e4d3aad9fa54b3cc8e7dd

2022-09-21 16:02 UTC, tech-bombo requested changes

2022-09-21 16:03 UTC, tech-bombo commented
El codigo esta bastante limpio solo unas pequeñas obs

2022-09-26 05:50 UTC, sebastianmendo1995 commented on src/pages/library/surveys/EditSurveyStepOne.js
> +      startAt: moment(data.startAt).format("YYYY-MM-DD HH:mm"),
por algun motivo cuando lo guardo como Date me da un error, podemos revisarlo juntos

2022-09-26 14:15 UTC, tech-bombo approved these changes

2022-09-26 14:28 UTC, merged