Admin company users
EBombo/ebombo-events pull request #79
Opened 2021-12-06 23:59 UTC by sebastianmendo1995

Admin company user

2021-12-06 23:59 UTC, tech-bombo commented
Task linked: [CU-1rwn2zv [events] Administración de usuarios](https://app.clickup.com/t/1rwn2zv)

2021-12-07 14:18 UTC, pyncior requested changes

2021-12-07 14:18 UTC, pyncior commented on src/firebase/config.js
> +  config.serverUrl = config.serverUrlLocal;
hay que volver a comentarlo despues de trabajar

2021-12-07 14:18 UTC, pyncior commented on src/pages/companies/_companyId/AdminCompanyUsers.js
> +  const { companyId } = router.query;
nit: quizas el query pueda ir justo debajo de router=useRouter

2021-12-07 14:18 UTC, pyncior commented on src/pages/companies/_companyId/AdminCompanyUsers.js
> +    console.log("excel");
Que se necesita para completar esto?

2021-12-07 14:18 UTC, pyncior commented on src/pages/companies/_companyId/AdminCompanyUsers.js
> +                <TabletUsers
simplificar a    <TabletUsers ...../>

2021-12-07 14:18 UTC, pyncior commented on src/pages/companies/_companyId/AdminCompanyUsers.js
> +            Content of Tab Pane 2
"Content of Tab Pane 2" asi se llama el tab en figma?

2021-12-07 14:18 UTC, pyncior commented on src/pages/companies/_companyId/ModalEditUser.js
> +  const { companyId } = router.query;
quizas el router.query puede estar justo abajo de   const router = useRouter();

2021-12-07 14:18 UTC, pyncior commented on src/pages/companies/_companyId/ModalInvite.js
> +  const { companyId } = router.query;
quizas el router.query; puede estar justo abajo de const router = useRouter();

2021-12-07 14:18 UTC, pyncior commented on src/pages/companies/_companyId/TabletUsers.js
> +      console.log(selectedUsers);
quitemos el console.log

2021-12-07 18:33 UTC, sebastianmendo1995 commented on src/pages/companies/_companyId/AdminCompanyUsers.js
> +            Content of Tab Pane 2
no hay diseño de esta parte en el figma, supongo que hay que ocultarlo de momento

2021-12-07 18:36 UTC, sebastianmendo1995 commented on src/firebase/config.js
> +  config.serverUrl = config.serverUrlLocal;
listo 👍

2021-12-07 18:37 UTC, sebastianmendo1995 commented on src/pages/companies/_companyId/ModalInvite.js
> +  const { companyId } = router.query;
listo 👍

2021-12-07 18:37 UTC, sebastianmendo1995 commented on src/pages/companies/_companyId/TabletUsers.js
> +      console.log(selectedUsers);
👍  listo

2021-12-09 19:23 UTC, sebastianmendo1995 commented on src/pages/companies/_companyId/AdminCompanyUsers.js
> +    console.log("excel");
listo, se implemento la functionalidad

2021-12-09 19:47 UTC, pyncior approved these changes
Buen trabajo 👍

2021-12-10 15:29 UTC, merged