Cu 1rwn9b4 events facturacin anthony arstegui
EBombo/ebombo-events pull request #87
Opened 2021-12-15 20:05 UTC by anargu

2021-12-15 20:05 UTC, tech-bombo commented
Task linked: [CU-1rwn9b4 [events] Facturación](https://app.clickup.com/t/1rwn9b4)

2021-12-16 18:34 UTC, pyncior requested changes

2021-12-16 18:34 UTC, pyncior commented on pages/users/[userId]/billing/index.js
> +const BillingDetailContainer = (props) => (
creo q este componente debe ir en companies y no en users

https://www.figma.com/file/dBKCBRTIFHbaIgUTRTDtlg/PERFIL?node-id=0%3A1

2021-12-16 18:34 UTC, pyncior commented on pages/users/[userId]/invoices/[invoiceId]/index.js
> +const InvoiceIdView = (props) => (
creo q este componente debe ir en companies y no en users

https://www.figma.com/file/dBKCBRTIFHbaIgUTRTDtlg/PERFIL?node-id=0%3A1

2021-12-16 18:34 UTC, pyncior commented on pages/users/[userId]/invoices/index.js
> +const AllInvoicesContainer = (props) => (
creo q este componente debe ir en companies y no en users

https://www.figma.com/file/dBKCBRTIFHbaIgUTRTDtlg/PERFIL?node-id=0%3A1

2021-12-16 18:34 UTC, pyncior commented on src/components/common/PlansPrices.js
> +    <PlanPriceContent plan={plan} color={plan.metadata.color} background={plan.metadata.background} key={index}>
procurar no usar el index como key a no ser que no tengamos mas opciones

2021-12-16 18:34 UTC, pyncior commented on src/components/common/PlansPrices.js
> +        {plan.metadata.recommended === "true" && <div className="header">Recomendado</div>}
el recommended lo haria un booleano para no usar el "true", se ve como raro xD

2021-12-16 18:34 UTC, pyncior commented on src/pages/users/_userId/Billing.js
> +      const activeSubscriptions = snapshotToArray(await getUserSubscriptions());
meteria lo de la funcion "getUserSubscriptions" a "getPlan"

const getPlan = async () => {
      const activeSubscriptionsQuery = await firestore
        .collection(`customers/${userId}/subscriptions`)
        .where("status", "==", "active")
        .orderBy("created", "desc")
        .get();
      
      const activeSubscriptions = snapshotToArray(activeSubscriptionsQuery);
      etc
}

si usaramos typescript nos pediria "getUserSubscriptions" como deps pero como no se usa en otro lado mejor de ponerlo dentro de la funcion

ademas que es mas facil leerlo

2021-12-16 18:34 UTC, pyncior commented on src/pages/users/_userId/billing/BillingOverview.js
> +      const _subscription = (await fetchUserSubscription()).data();
igual aqui pondre lo de la funcion "fetchUserSubscription" dentro de "fetchUserSubscription" por que no se usa en otro lado

2021-12-16 18:34 UTC, pyncior commented on src/pages/users/_userId/billing/BillingOverview.js
> +      const invoices = snapshotToArray(await fetchLastInvoice());
igual aqui "fetchLastInvoice" dentro de "getInvoice"

2021-12-16 18:34 UTC, pyncior commented on src/pages/users/_userId/billing/BillingOverview.js
> +      const _paymentInformation = (await fetchPaymentInformation(_invoice['payment_intent'])).data();
e igual aqui "fetchPaymentInformation" dentro de "getInvoice"

2021-12-16 18:34 UTC, pyncior commented on src/pages/users/_userId/billing/BillingOverview.js
> +      await goToPortalLink();
agregar un comentario para no estar yendo al file para saber que exactamente hace ayudaria

2021-12-16 18:34 UTC, pyncior commented on src/pages/users/_userId/billing/SubscriptionPlans.js
> +export const SubscriptionPlans = (props) => {
creo que estos archivos deben estar en companies que es donde tiene el tab de factura y no en users, a revisar el figma para confirmar

2021-12-16 18:34 UTC, pyncior commented on src/pages/users/_userId/billing/SubscriptionPlans.js
> +        const activePrices = snapshotToArray(await fetchAllActivePrices());
igual llevaria "fetchAllActivePrices" a dentro de "fetchPlans", no se usa en otro lado

2021-12-16 18:34 UTC, pyncior commented on src/pages/users/_userId/invoices/InvoiceTable.js
> +      const subcriptions = await fetchSubscriptions();
traer su pasos dentro de la funcion si no se llama en otro lado

2021-12-16 18:34 UTC, pyncior commented on src/stripe/helpers.js
> +  return new Promise((resolve, reject) => {
No se que tan necesario es hacer esto, quizas bastaria con un try catch sobre el add a firebase, si este no procede lanzara una excepcion y sera capturado pro el try catch

2021-12-16 18:34 UTC, pyncior commented on src/stripe/helpers.js
> +  return new Promise((resolve, reject) => {
se esta creando una promesa que resolvera despues de una promesa, mejor de usar una sola sin el then, quizas sea mas facil leer y en lineas mas cortas usando async await, a evaluar si es necesario

2021-12-16 18:34 UTC, pyncior commented on src/stripe/helpers.js
> +export const formatAmount = (price) => (price / 100)?.toFixed(2);
el . toFixed(X) convierte el numero en string, si no hay problema que este se vuelva un string ignora mi comentario, de lo contrario podria causar problemas, que se pueden solicionar con un + delante del retorno de dato

export const formatAmount = (price) => +(price / 100)?.toFixed(2);

2021-12-16 20:15 UTC, anargu commented on src/stripe/helpers.js
> +export const formatAmount = (price) => (price / 100)?.toFixed(2);
Opto por agregar el más (+) para operaciones matemáticas en caso se requiere. Por el momento el format es utilizado para mostrar los números, no para operar.

El Fixed fue utilizado para mitigar el error al hacer operaciones y den un resultado extraño. Adjunto imagen:

![image](https://user-images.githubusercontent.com/7935037/146442671-17763598-74da-48cc-8e43-f258fb481f90.png)

2021-12-16 20:22 UTC, anargu commented on src/components/common/PlansPrices.js
> +        {plan.metadata.recommended === "true" && <div className="header">Recomendado</div>}
Entiendo perfectamente, sucede que este objeto proviene de Stripe (los planes) y en la plataforma te permite alojar datos extra en la metadata del plan y como tal aloja por defecto todo a String y es así como se recibe en el cliente.

Lo que pensé en un inicio es engullir todo en un campo todos los datos JSON "stringified" en metadata, pero quería mantener esos campos de fácil manipulación para que cualquier administrador puede cómodamente modificar esos datos en caso requiera.

Lo otro sería crear constantes en datalist de valores predeterminados de estos campos para que seamos menos propensos al error humano (error-prone).

2021-12-16 21:41 UTC, anargu commented on src/stripe/helpers.js
> +  return new Promise((resolve, reject) => {
Para poder tener un mayor control de procesos asíncronos como el onSnapshot sobre la referencia del documento he dado con enmascararlo en una promesa para así devolver el resultado. Se manda a escuchar porque stripe hace un cambio sobre el mismo documento unos segundos después.

2021-12-17 14:32 UTC, anargu commented on src/pages/users/_userId/invoices/InvoiceTable.js
> +      setInvoices(snapshotToArray(await fetchInvoices(subscriptionId)));
FetchInvoices se invoca en 2 secciones diferentes por lo que se mantendría la función

2021-12-20 22:40 UTC, anargu commented on src/pages/users/_userId/invoices/InvoiceTable.js
> +const downloadPdf = (pdfUrl) => window.open(pdfUrl, "blank");
Se procedió a usar Anchors con target _blank para simular el mismo procedimiento para descargar invoice

2022-01-03 13:56 UTC, pyncior approved these changes

2022-01-03 13:56 UTC, pyncior commented on src/pages/companies/_companyId/billing/SubscriptionPlans.js
> +  });
nit: Aveces la falta de deps en los useEffect causa problemas useEffect(()=>{},"[]");

2022-01-06 22:36 UTC, merged