new hanged
EBombo/ebombo-events pull request #91
Opened 2021-12-28 22:58 UTC by sebastianmendo1995

Modifying modal settings so can be used with multiple games

2021-12-28 22:58 UTC, tech-bombo commented
Task linked: [CU-21pux9t [crear hanged] nueva distribucion de creacion de juego de ahorcado](https://app.clickup.com/t/21pux9t)

2021-12-28 23:56 UTC, pyncior requested changes

2021-12-28 23:56 UTC, pyncior commented on src/pages/library/games/_gameId/Hanged.js
> +  const [ownBranding, setOwnBranding] = useState(props.game?.ownBranding ?? false);
esto puede ser: 
  const [ownBranding, setOwnBranding] = useState(!!props.game?.ownBranding);

2021-12-28 23:56 UTC, pyncior commented on src/pages/library/games/_gameId/Hanged.js
> -  const [newId] = useState(props.game ? props.game.id : firestore.collection("hanged").doc().id);
quizas esto pueda ser un useMemo, para prevenir generar id en caso de se renderice el componente
  const newId = useMemo(()=>{
      return props.game?.id ?? firestore.collection("hanged").doc().id;
 },[props.game]);

2021-12-28 23:56 UTC, pyncior commented on src/pages/library/games/_gameId/Hanged.js
> +  const [newId] = useState(props.game?.id ?? firestore.collection("hanged").doc().id);
esto tmb podria ser un useMemo
[tomar el ejemplo de arriba]

2021-12-28 23:56 UTC, pyncior commented on src/pages/library/games/_gameId/Bingo.js
> +          path={`/games/Bingo/${props.newId}`}
lar rutas sean URL o para el STORAGE deben ser en lowercase separadas por guiones

2021-12-29 00:00 UTC, pyncior requested changes
-No guarda lo editado [ni palabras clave, ni titulo]
-Al guardar debe hacer un goBack o mostrar una notificacion de que se guardo con exito

https://user-images.githubusercontent.com/55215092/147615712-1668edeb-0e28-4a4b-a0e5-d971282d8500.mov

2021-12-29 00:03 UTC, pyncior requested changes
probar la edicion y creacion el flujo normal, tambien probar en mobile y asegurarse que este funcionando correctamente en la mayor cantidad de escenarios

2022-01-03 16:47 UTC, pyncior approved these changes

2022-01-06 14:57 UTC, merged